version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Fetching Cache Version
          command: echo $CACHE_VERSION > cache_version
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ checksum "cache_version" }}
      - run:
          name: Installing Dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          paths:
            - ~/repo/node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ checksum "cache_version" }}
      - run:
          name: Removing Cache Version file
          command: rm cache_version
      - run:
          name: Prettying and Linting
          command: yarn prettier es6 --write src/**/*.js && yarn lint
      - run:
          name: Static Checking and Testing
          command: yarn validate
      - run:
          name: Building
          command: yarn build
      - run:
          name: Generating Coveralls Report
          command: yarn report-coverage
